src/django_namespaces/urls.py
from __future__ import annotations

from django.urls import path

from .views import clear_namespaces_view
from .views import namespace_activation_view
from .views import NamespaceCreateView
from .views import NamespaceDeleteConfirmationView
from .views import NamespaceDetailUpdateView
from .views import NamespaceListView

app_name = "django_namespaces"
urlpatterns = [
    path("", NamespaceListView.as_view(), name="list"),
    path("create/", NamespaceCreateView.as_view(), name="create"),
    path("clear/", clear_namespaces_view, name="clear"),
    path(
        "<slug:handle>/",
        NamespaceDetailUpdateView.as_view(),
        name="detail-update",
    ),
    path("<slug:handle>/activate/", namespace_activation_view, name="activate"),
    path(
        "<slug:handle>/confirm-delete/",
        NamespaceDeleteConfirmationView.as_view(),
        name="delete",
    ),
]

src/django_namespaces/templates/django_namespaces/namespace_create.html
{% extends "base.html" %}


{% block content %}

<h1>Create a new namespace</h1>
{% include 'django_namespaces/snippets/namespace_create.html' %}

{% endblock %}

src/django_namespaces/templates/django_namespaces/namespace_delete.html
{% extends "base.html" %}


{% block content %}

<div>

{% include 'django_namespaces/snippets/namespace_update.html' with object=object form=form %}
</div>

<div style="border:1px solid red;border-radius: 3rem; padding: 2rem; margin: 2rem auto; text-align: center;">
    <form action="{{ object.get_delete_url}}" method="POST">
        {% csrf_token %}
    
    <h1>Delete {{ object.namespace }}?</h1>
    <p>This action cannot be undone and might have unintended consequences.</p>
    <input type='submit' value='Yes, delete.'>
    <a href="{{ object.get_absolute_url }}">Cancel</a>
</form>
</div>

{% endblock %}

src/django_namespaces/templates/django_namespaces/namespace_list.html
{% extends "base.html" %}


{% block content %}

<h1>Namespace List</h1>
<div>
    <a href="{% url 'django_namespaces:create' %}">Create a new namespace</a>
</div>
{% include "django_namespaces/snippets/namespace_list.html" with object_list=object_list %}
{% endblock content %}

src/django_namespaces/templates/django_namespaces/namespace_needs_activation.html
{% extends "base.html" %}

{% block content %}
    <h1>Namespace Required</h1>
    <p>You need to activate a namespace before accessing this view. Please visit the namespaces page to activate a namespace.</p>
{% endblock %}

src/django_namespaces/templates/django_namespaces/namespace_update.html
{% extends "base.html" %}


{% block content %}

<div>
<h1>Update {{ object.namespace }}</h1>
{% include 'django_namespaces/snippets/namespace_update.html' with object=object form=form %}
</div>

<div style="border:1px solid red;border-radius: 3rem; padding: 2rem; margin: 2rem auto; text-align: center;">
    <h3 style="padding:0px; margin:4px auto;">Danger Zone</h3>
    <a href="{{ object.get_delete_url }}">Delete namespace</a>
</div>

{% endblock %}